config/routes.rb
Rails.application.routes.draw do

  root 'animals#index'

  get 'searchform', to: "sightings#searchform"
  get 'search', to: "sightings#search"
  get 'searchrange', to: "sightings#searchrange"
  resources :animals do
    resources :sightings
  end

  resources :regions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  
  has_many :sightings, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3 }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/region.rb
class Region < ApplicationRecord
  
  validates :name, presence: true, length: { minimum: 3 }

end

app/models/sighting.rb
class Sighting < ApplicationRecord
belongs_to :animal

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    @animals = Animal.all
  end

  def show
    @animal = Animal.find(params[:id])
  end

  

  def new
    @animal = Animal.new
    
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to @animal
    else
      render 'new'
    end
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
   
    if @animal.update(animal_params)
      redirect_to @animal
    else
      render 'edit'
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
 
    redirect_to animals_path
  end

  private
  def animal_params
    params.require(:animal).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController


  def index
    @regions = Region.all
  end

  def show
    @region = Region.find(params[:id])
  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      redirect_to @region
    else
      render 'new'
    end
  end

  def edit
    @region = Region.find(params[:id])
  end

  def update
    @region = Region.find(params[:id])
   
    if @region.update(region_params)
      redirect_to @region
    else
      render 'edit'
    end
  end

  def destroy
    @region = Region.find(params[:id])
    @region.destroy
 
    redirect_to regions_path
  end

  private
  def region_params
    params.require(:region).permit(:name)
  end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController


  def index 
    @sightings = Sighting.all

  end

  def search
    
    @sightings = Sighting.where("region LIKE ?", "%" + params[:q] + "%")

  end 

  def searchrange
    start_date = format_date_string('start_date')
    end_date = format_date_string('end_date')
   
    # @sightings = Sighting.where(date: Date.today - 2.days..Date.today)
    @sightings = Sighting.where(date: start_date..end_date)
  end 

  def searchform
    
  end 

  def new 
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.new

  end

  def create
    
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.create(sighting_params)
    redirect_to animal_path(@animal)
  end

  def destroy
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.find(params[:id])
    @sighting.destroy
    redirect_to animal_path(@animal)
  end
 
  private
    def sighting_params
      params.require(:sighting).permit(:date, :latitude, :longitude, :region)
    end

    def format_date_string(date)
      DateTime.parse(params[:sightings]["#{date}(1i)"] + '-' + params[:sightings]["#{date}(2i)"] + '-' + params[:sightings]["#{date}(3i)"] + ' ' + params[:sightings]["#{date}(4i)"] + ":" + params[:sightings]["#{date}(5i)"])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<%= form_with model: @animal, local: true do |form| %>
 
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@animal.errors.count, "error") %> prohibited
        this animal from being inserted:
      </h2>
      <ul>
        <% @animal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/animals/edit.html.erb
<h1>Edit Animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path%>

app/views/animals/index.html.erb
<h1> Animals </h1>


<table class="table">
  <thead>
    <tr>
      
      <th scope="col">Animal</th>
      
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @animals.each do |animal| %>
    <tr>
      <td><%= animal.name %></td>
      <td><%= link_to 'Show', animal_path(animal) %> | <%= link_to 'Edit', edit_animal_path(animal)%> | <%= link_to 'Destroy', animal_path(animal),
              method: :delete,
              data: { confirm: 'Are you sure?' }%> </td>
    </tr>
  <% end %>
    
  </tbody>
</table>
 


<p>
<%= link_to 'Insert New Animal', new_animal_path %>
</p>

<p>
<%= link_to 'Go To Regions', regions_path %>
</p>

app/views/animals/new.html.erb
<h1>Insert New Animal</h1>

<%= render 'form' %>


<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @animal.name %></h1>
  <p class="lead"><%= link_to 'Index', animals_path %> | <%= link_to 'Edit', edit_animal_path(@animal)%> | <%= link_to 'Destroy', animal_path(@animal),
              method: :delete,
              data: { confirm: 'Are you sure?' }%> </p>

  


  <hr class="my-4">

  <h2 class="pb-5">Sightings</h2>

  <p><%= render @animal.sightings %></p>
 
  
  <%= link_to 'Add New Sighting', new_animal_sighting_path(@animal), :class => "btn btn-primary btn-md" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">WildlifeTracker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-link active"> <%= link_to 'Animals', animals_path %> </a>
      
      <a class="nav-link"><%= link_to 'Regions', regions_path %></a>
      <a class="nav-link"><%= link_to 'Search', '/searchform' %></a>

      
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

  </body>
</html>

app/views/regions/_form.html.erb
<%= form_with model: @region, local: true do |form| %>
 
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@region.errors.count, "error") %> prohibited
        this region from being inserted:
      </h2>
      <ul>
        <% @region.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/regions/edit.html.erb
<h1>Edit Region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path%>

app/views/regions/index.html.erb
<h1> Regions </h1>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Region</th>
      <th scope="col"></th>
      
    </tr>
  </thead>
  <tbody>
  <% @regions.each do |region| %>
    <tr>
      <td><%= region.name %></td>
      <td><%= link_to 'Show', region_path(region) %> | <%= link_to 'Edit', edit_region_path(region)%> | <%= link_to 'Destroy', region_path(region),
              method: :delete,
              data: { confirm: 'Are you sure?' }%> </td>
    </tr>
  <% end %>
    
  </tbody>
</table>
 

<p>
<%= link_to 'Insert New Region', new_region_path %>
</p>

<p>
<%= link_to 'Go To Animals', animals_path %>
</p>

app/views/regions/new.html.erb
<h1>Insert New Region</h1>

<%= render 'form' %>


<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @region.name %></h1>
  <p class="lead"><%= link_to 'Index', regions_path %> | <%= link_to 'Edit', edit_region_path(@region)%> | <%= link_to 'Destroy', region_path(@region),
              method: :delete,
              data: { confirm: 'Are you sure?' }%></p>
  <hr class="my-4">
  <p></p>
  <a class="btn btn-primary btn-md" href="#" role="button">Add New Sighting</a>
</div>

<%= link_to 'Index', regions_path %> | <%= link_to 'Edit', edit_region_path(@region)%> | <%= link_to 'Destroy', region_path(@region),
              method: :delete,
              data: { confirm: 'Are you sure?' }%>

app/views/sightings/_form.html.erb
<%= form_with(model: [ @animal, @animal.sightings.build ], local: true) do |form| %>
  <p>
    <%= form.label :date %><br>
    <%= form.datetime_select :date, { ampm: true, order: [:day, :month, :year] } %>
  </p>
  <p>
    <%= form.label :longitude %><br>
    <%= form.text_field :longitude %>
  </p>
  <p>
    <%= form.label :latitude %><br>
    <%= form.text_field :latitude %>
  </p>

  <p>
  <%= form.select :region, Region.all.collect { |r| [ r.name, r.name ] } %>
  </p>


  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/sightings/_sighting.html.erb
  <p>
    <strong>Date:</strong>
    <%= sighting.date %>
  </p>
 
  <p>
    <strong>Longitude:</strong>
    <%= sighting.longitude %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= sighting.latitude %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= sighting.region %>
  </p>

  

  <p>
  <%= link_to 'Destroy Sighting', [sighting.animal, sighting],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </p>

  <hr />

app/views/sightings/index.html.erb
<h1>All Sightings</h1>
<table class="table">
  <thead>
    <tr>
      
      <th scope="col">Animal</th>
      
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @animals.each do |animal| %>
    <tr>
      <td><%= animal.name %></td>
      <td><%= link_to 'Show', animal_path(animal) %> | <%= link_to 'Edit', edit_animal_path(animal)%> | <%= link_to 'Destroy', animal_path(animal),
              method: :delete,
              data: { confirm: 'Are you sure?' }%> </td>
    </tr>
  <% end %>
    
  </tbody>
</table>

app/views/sightings/new.html.erb
<h2>Add a sighting:</h2>
<%= render 'sightings/form'%>

app/views/sightings/search.html.erb
<div class="row col-md-12">
<div class="col-md-6 pr-5">
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search by region:") %> 
  <%= select_tag(:q, options_for_select([["Select Region", "Select Region"]] + Region.all.collect { |r| [ r.name, r.name ] }))%>
  <%= submit_tag("Search") %>
<% end %>

</div>

<div class="col-md-6">

<%= form_tag("/searchrange", method: "get") do %>

<p>
<%= label_tag(:q, "Search by date range: ")  %>
</p>

  <p>
    <%= label_tag(:q, "Start")  %><br>
    
    <%= datetime_select(:start, { ampm: true, order: [:day, :month, :year] }) %>
   
  </p>
  <p>
  <%= label_tag(:q, "End")  %><br>
    
    <%= datetime_select(:end, { ampm: true, order: [:day, :month, :year] }) %>
  </p>

  <p>
    <%= submit_tag("Search") %>
  </p>
<% end %>
</div>

</div>


<h1>Search results</h1>


  <%= render @sightings %>

  

<%= link_to 'Animals Home', animals_path %> | <%= link_to 'Regions Home', regions_path %>

app/views/sightings/searchform.html.erb
<div class="row col-md-12">
<div class="col-md-6 pr-5">
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search by region:") %> 
  <%= select_tag(:q, options_for_select([["Select Region", "Select Region"]] + Region.all.collect { |r| [ r.name, r.name ] }))%>
  <%= submit_tag("Search") %>
<% end %>

</div>

<div class="col-md-6">

<%= form_tag("/searchrange", method: "get") do %>

<p>
<%= label_tag(:q, "Search by date range: ")  %>
</p>

  <p>
    <%= label_tag(:q, "Start")  %><br>
    
     
     <%= datetime_select("sightings", "start_date") %>
   
  </p>
  <p>
  <%= label_tag(:q, "End")  %><br>
    
    <%# <%= datetime_select(:end, { ampm: true, order: [:day, :month, :year] }) %>
    <%= datetime_select("sightings", "end_date") %>
  </p>

  <p>
    <%= submit_tag("Search") %>
  </p>
<% end %>
</div>

</div>

app/views/sightings/searchrange.html.erb
<h1>Results by range</h1>

<%= render @sightings %>